import pkg from 'pg';
const { Client } = pkg;

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error('DATABASE_URL is required.');
}

const client = new Client({
  connectionString
});

async function main() {
  await client.connect();
  console.log('✅ Connected to Supabase to enable pgvector and RAG extensions');

  try {
    await client.query("CREATE EXTENSION IF NOT EXISTS vector;");
    console.log('🚀 PGVector extension enabled.');

    await client.query("ALTER TABLE public.yatra_destination_cache ADD COLUMN IF NOT EXISTS embedding vector(384);");
    console.log('🧬 Vector embedding column added to yatra_destination_cache.');

    const createRpc = "CREATE OR REPLACE FUNCTION match_yatra_destinations (query_embedding vector(384), match_threshold float, match_count int) RETURNS TABLE (id bigint, name text, type text, tier text, metadata jsonb, similarity float) LANGUAGE plpgsql AS $$ BEGIN RETURN QUERY SELECT y.id, y.name, y.type, y.tier, y.metadata, 1 - (y.embedding <=> query_embedding) AS similarity FROM public.yatra_destination_cache y WHERE 1 - (y.embedding <=> query_embedding) > match_threshold ORDER BY y.embedding <=> query_embedding LIMIT match_count; END; $$;";
    await client.query(createRpc);
    console.log('🧠 Semantic Search RPC Function created successfully!');

    // Create Waitlist Table Without NOT EXISTS syntax error (it's IF NOT EXISTS)
    const createWaitlist = "CREATE TABLE IF NOT EXISTS public.yatra_waitlist_analytics (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, pnr text, train_number text, initial_status text, current_status text, probability float, last_checked timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL, user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE);";
    await client.query(createWaitlist);
    console.log('🚆 Waitlist Prediction Analytics table created successfully!');

  } catch (err) {
    console.error('❌ Migration Error:', err.message);
  } finally {
    await client.end();
  }
}

main().catch(console.error);
